/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardAnalyticsRouteImport } from './routes/_dashboard.analytics'
import { Route as DashboardConnectionsRouteImport } from './routes/_dashboard.connections'
import { Route as DashboardModelsRouteImport } from './routes/_dashboard.models'
import { Route as DashboardReviewsRouteImport } from './routes/_dashboard.reviews'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConnectionsRoute = DashboardConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardModelsRoute = DashboardModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof DashboardAnalyticsRoute
  '/connections': typeof DashboardConnectionsRoute
  '/models': typeof DashboardModelsRoute
  '/reviews': typeof DashboardReviewsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/analytics': typeof DashboardAnalyticsRoute
  '/connections': typeof DashboardConnectionsRoute
  '/models': typeof DashboardModelsRoute
  '/reviews': typeof DashboardReviewsRoute
  '/': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/analytics': typeof DashboardAnalyticsRoute
  '/_dashboard/connections': typeof DashboardConnectionsRoute
  '/_dashboard/models': typeof DashboardModelsRoute
  '/_dashboard/reviews': typeof DashboardReviewsRoute
  '/_dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/analytics' | '/connections' | '/models' | '/reviews'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/analytics' | '/connections' | '/models' | '/reviews' | '/'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/analytics'
    | '/_dashboard/connections'
    | '/_dashboard/models'
    | '/_dashboard/reviews'
    | '/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/analytics': {
      id: '/_dashboard/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/connections': {
      id: '/_dashboard/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof DashboardConnectionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/models': {
      id: '/_dashboard/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof DashboardModelsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/reviews': {
      id: '/_dashboard/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardConnectionsRoute: typeof DashboardConnectionsRoute
  DashboardModelsRoute: typeof DashboardModelsRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardConnectionsRoute: DashboardConnectionsRoute,
  DashboardModelsRoute: DashboardModelsRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
