export const DASHBOARD_PASSWORD_MINIMUM_LENGTH = 8;
export const DASHBOARD_PASSWORD_MAXIMUM_LENGTH = 256;
export const DASHBOARD_SESSION_TOKEN_BYTES = 32;
export const DASHBOARD_SESSION_TOKEN_MINIMUM_LENGTH = 43;
export const DASHBOARD_SESSION_TOKEN_MAXIMUM_LENGTH = 64;
export const DASHBOARD_SESSION_DURATION_MS = 8 * 60 * 60 * 1_000;
export const DASHBOARD_AUTH_REQUEST_MAXIMUM_BYTES = 4_096;
